version: "3"
services:
  app:
    image: skyride/reve-flairs:1.2.1
    restart: always
    env_file:
      - .env
    volumes:
      - media:/media
    ports:
      - ${PORT}:${PORT}

volumes:
  media:
