# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('ticker', models.CharField(max_length=5)),
                ('logo', models.ImageField(upload_to='alliances')),
            ],
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('ticker', models.CharField(max_length=5)),
                ('logo', models.ImageField(upload_to='corps')),
            ],
        ),
    ]
