# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171115_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='corp_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='corp',
            name='member_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
