# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171115_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
