# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171115_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='corp',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
