# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='corp_spite',
            new_name='corp_sprite',
        ),
    ]
