# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171116_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='active_chars',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='characters',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='recent_kills',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='ships_destroyed',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
