# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171116_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='generics')),
            ],
        ),
    ]
