# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_generic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RedditorFlair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Alliance')),
                ('corp', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Corp')),
                ('generic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Generic')),
                ('redditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flairs', to='core.Redditor')),
            ],
        ),
    ]
