# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_redditor_redditorflair'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditorflair',
            name='ended',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='redditorflair',
            name='started',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
