# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171212_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditorflair',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redditorflairs', to='core.Alliance'),
        ),
        migrations.AlterField(
            model_name='redditorflair',
            name='corp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redditorflairs', to='core.Corp'),
        ),
        migrations.AlterField(
            model_name='redditorflair',
            name='generic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redditorflairs', to='core.Generic'),
        ),
    ]
