name: Publish Docker
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: "Set env"
      run: echo ::set-env name=TAG::${GITHUB_REF#refs/*/}

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: skyride/reve-flairs
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        buildargs: TAG
    
    - name: Create Sentry Release
      env:
        SENTRY_RELEASE_URL: ${{ secrets.SENTRY_RELEASE_URL }}
      run: |
        curl ${SENTRY_RELEASE_URL} \
          -X POST \
          -H 'Content-Type: application/json' \
          -d "{\"version\": \"${TAG}\"}"
